version: '2'
services:
  api:
    build:
      context: ./
      args:
        NODE_ENV: development
    command: /bin/sh -c "npm run migrate && npm run start"
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
  postgres:
    image: postgres:10.2-alpine
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
<<<<<<< HEAD
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
=======
      - 5432:5432
    environment:
      POSTGRES_USER: rytmi
      POSTGRES_PASSWORD: rytmi
      POSTGRES_DB: rytmi
      
>>>>>>> changed test to use pg
